from __future__ import annotations

"""Static discovery/search config for the lead machine."""

COLORADO_SEARCH_LOCATIONS = [
    {"name": "Fort Collins, CO", "lat": 40.5853, "lng": -105.0844},
    {"name": "Denver, CO", "lat": 39.7392, "lng": -104.9903},
    {"name": "Colorado Springs, CO", "lat": 38.8339, "lng": -104.8214},
    {"name": "Boulder, CO", "lat": 40.0150, "lng": -105.2705},
    {"name": "Greeley, CO", "lat": 40.4233, "lng": -104.7091},
    {"name": "Loveland, CO", "lat": 40.3978, "lng": -105.0749},
    {"name": "Longmont, CO", "lat": 40.1672, "lng": -105.1019},
    {"name": "Pueblo, CO", "lat": 38.2544, "lng": -104.6091},
    {"name": "Grand Junction, CO", "lat": 39.0639, "lng": -108.5506},
    {"name": "Durango, CO", "lat": 37.2753, "lng": -107.8801},
    {"name": "Steamboat Springs, CO", "lat": 40.4850, "lng": -106.8317},
    {"name": "Glenwood Springs, CO", "lat": 39.5505, "lng": -107.3248},
    {"name": "Aspen, CO", "lat": 39.1911, "lng": -106.8175},
    {"name": "Vail, CO", "lat": 39.6433, "lng": -106.3781},
    {"name": "Breckenridge, CO", "lat": 39.4817, "lng": -106.0384},
    {"name": "Castle Rock, CO", "lat": 39.3722, "lng": -104.8561},
    {"name": "Aurora, CO", "lat": 39.7294, "lng": -104.8319},
    {"name": "Lakewood, CO", "lat": 39.7047, "lng": -105.0814},
    {"name": "Littleton, CO", "lat": 39.6133, "lng": -105.0166},
    {"name": "Thornton, CO", "lat": 39.8680, "lng": -104.9719},
    {"name": "Arvada, CO", "lat": 39.8028, "lng": -105.0875},
    {"name": "Brighton, CO", "lat": 39.9853, "lng": -104.8205},
    {"name": "Broomfield, CO", "lat": 39.9205, "lng": -105.0867},
    {"name": "Centennial, CO", "lat": 39.5792, "lng": -104.8769},
    {"name": "Golden, CO", "lat": 39.7555, "lng": -105.2211},
    {"name": "Lafayette, CO", "lat": 39.9936, "lng": -105.0897},
    {"name": "Louisville, CO", "lat": 39.9778, "lng": -105.1319},
    {"name": "Leadville, CO", "lat": 39.2508, "lng": -106.2925},
    {"name": "Gunnison, CO", "lat": 38.5458, "lng": -106.9253},
    {"name": "Montrose, CO", "lat": 38.4783, "lng": -107.8762},
    {"name": "Pagosa Springs, CO", "lat": 37.2695, "lng": -107.0098},
    {"name": "Parker, CO", "lat": 39.5186, "lng": -104.7614},
    {"name": "Rifle, CO", "lat": 39.5347, "lng": -107.7831},
    {"name": "Salida, CO", "lat": 38.5347, "lng": -105.9989},
    {"name": "Sterling, CO", "lat": 40.6255, "lng": -103.2077},
    {"name": "Telluride, CO", "lat": 37.9375, "lng": -107.8123},
    {"name": "Trinidad, CO", "lat": 37.1695, "lng": -104.5005},
    {"name": "Westminster, CO", "lat": 39.8367, "lng": -105.0372},
    {"name": "Windsor, CO", "lat": 40.4775, "lng": -104.9014},
    {"name": "Woodland Park, CO", "lat": 38.9939, "lng": -105.0569},
    {"name": "Canon City, CO", "lat": 38.4410, "lng": -105.2425},
]

SOUTHERN_CALIFORNIA_SEARCH_LOCATIONS = [
    {"name": "Los Angeles, CA", "lat": 34.0522, "lng": -118.2437},
    {"name": "Long Beach, CA", "lat": 33.7701, "lng": -118.1937},
    {"name": "Anaheim, CA", "lat": 33.8366, "lng": -117.9143},
    {"name": "Santa Ana, CA", "lat": 33.7455, "lng": -117.8677},
    {"name": "Irvine, CA", "lat": 33.6846, "lng": -117.8265},
    {"name": "Huntington Beach, CA", "lat": 33.6595, "lng": -117.9988},
    {"name": "Newport Beach, CA", "lat": 33.6189, "lng": -117.9289},
    {"name": "Costa Mesa, CA", "lat": 33.6411, "lng": -117.9187},
    {"name": "Fullerton, CA", "lat": 33.8704, "lng": -117.9242},
    {"name": "Torrance, CA", "lat": 33.8358, "lng": -118.3406},
    {"name": "Pasadena, CA", "lat": 34.1478, "lng": -118.1445},
    {"name": "Glendale, CA", "lat": 34.1425, "lng": -118.2551},
    {"name": "Burbank, CA", "lat": 34.1808, "lng": -118.3090},
    {"name": "Santa Monica, CA", "lat": 34.0195, "lng": -118.4912},
    {"name": "San Diego, CA", "lat": 32.7157, "lng": -117.1611},
    {"name": "Chula Vista, CA", "lat": 32.6401, "lng": -117.0842},
    {"name": "Oceanside, CA", "lat": 33.1959, "lng": -117.3795},
    {"name": "Carlsbad, CA", "lat": 33.1581, "lng": -117.3506},
    {"name": "Escondido, CA", "lat": 33.1192, "lng": -117.0864},
    {"name": "Riverside, CA", "lat": 33.9806, "lng": -117.3755},
    {"name": "San Bernardino, CA", "lat": 34.1083, "lng": -117.2898},
    {"name": "Ontario, CA", "lat": 34.0633, "lng": -117.6509},
    {"name": "Rancho Cucamonga, CA", "lat": 34.1064, "lng": -117.5931},
    {"name": "Corona, CA", "lat": 33.8753, "lng": -117.5664},
    {"name": "Temecula, CA", "lat": 33.4936, "lng": -117.1484},
    {"name": "Murrieta, CA", "lat": 33.5539, "lng": -117.2139},
    {"name": "Palm Springs, CA", "lat": 33.8303, "lng": -116.5453},
    {"name": "Ventura, CA", "lat": 34.2746, "lng": -119.2290},
    {"name": "Oxnard, CA", "lat": 34.1975, "lng": -119.1771},
    {"name": "Thousand Oaks, CA", "lat": 34.1706, "lng": -118.8376},
    {"name": "Santa Barbara, CA", "lat": 34.4208, "lng": -119.6982},
]

ORANGE_COUNTY_SAN_DIEGO_SEARCH_LOCATIONS = [
    {"name": "Newport Beach, CA", "lat": 33.6189, "lng": -117.9289},
    {"name": "Huntington Beach, CA", "lat": 33.6595, "lng": -117.9988},
    {"name": "Irvine, CA", "lat": 33.6846, "lng": -117.8265},
    {"name": "Corona del Mar, CA", "lat": 33.5992, "lng": -117.8731},
    {"name": "Laguna Beach, CA", "lat": 33.5427, "lng": -117.7854},
    {"name": "Lake Forest, CA", "lat": 33.6469, "lng": -117.6892},
    {"name": "Mission Viejo, CA", "lat": 33.6000, "lng": -117.6720},
    {"name": "San Juan Capistrano, CA", "lat": 33.5017, "lng": -117.6626},
    {"name": "Laguna Hills, CA", "lat": 33.5917, "lng": -117.6992},
    {"name": "Laguna Niguel, CA", "lat": 33.5225, "lng": -117.7076},
    {"name": "Aliso Viejo, CA", "lat": 33.5677, "lng": -117.7256},
    {"name": "Dana Point, CA", "lat": 33.4669, "lng": -117.6981},
    {"name": "San Clemente, CA", "lat": 33.4270, "lng": -117.6120},
    {"name": "Carlsbad, CA", "lat": 33.1581, "lng": -117.3506},
    {"name": "Chula Vista, CA", "lat": 32.6401, "lng": -117.0842},
    {"name": "Coronado, CA", "lat": 32.6859, "lng": -117.1831},
    {"name": "Del Mar, CA", "lat": 32.9595, "lng": -117.2653},
    {"name": "El Cajon, CA", "lat": 32.7948, "lng": -116.9625},
    {"name": "Encinitas, CA", "lat": 33.0370, "lng": -117.2920},
    {"name": "Escondido, CA", "lat": 33.1192, "lng": -117.0864},
    {"name": "Imperial Beach, CA", "lat": 32.5839, "lng": -117.1131},
    {"name": "La Mesa, CA", "lat": 32.7678, "lng": -117.0231},
    {"name": "Lemon Grove, CA", "lat": 32.7426, "lng": -117.0314},
    {"name": "National City, CA", "lat": 32.6781, "lng": -117.0992},
    {"name": "Oceanside, CA", "lat": 33.1959, "lng": -117.3795},
    {"name": "Poway, CA", "lat": 32.9628, "lng": -117.0359},
    {"name": "San Diego, CA", "lat": 32.7157, "lng": -117.1611},
    {"name": "San Marcos, CA", "lat": 33.1434, "lng": -117.1661},
    {"name": "Santee, CA", "lat": 32.8384, "lng": -116.9739},
    {"name": "Solana Beach, CA", "lat": 32.9912, "lng": -117.2711},
    {"name": "Vista, CA", "lat": 33.2000, "lng": -117.2425},
]

NORTHERN_CENTRAL_CALIFORNIA_SEARCH_LOCATIONS = [
    {"name": "San Francisco, CA", "lat": 37.7749, "lng": -122.4194},
    {"name": "San Jose, CA", "lat": 37.3382, "lng": -121.8863},
    {"name": "Oakland, CA", "lat": 37.8044, "lng": -122.2712},
    {"name": "Sacramento, CA", "lat": 38.5816, "lng": -121.4944},
    {"name": "Fresno, CA", "lat": 36.7378, "lng": -119.7871},
    {"name": "Bakersfield, CA", "lat": 35.3733, "lng": -119.0187},
    {"name": "Stockton, CA", "lat": 37.9577, "lng": -121.2908},
    {"name": "Modesto, CA", "lat": 37.6391, "lng": -120.9969},
    {"name": "Santa Rosa, CA", "lat": 38.4405, "lng": -122.7144},
    {"name": "Salinas, CA", "lat": 36.6777, "lng": -121.6555},
    {"name": "Monterey, CA", "lat": 36.6002, "lng": -121.8947},
    {"name": "Santa Cruz, CA", "lat": 36.9741, "lng": -122.0308},
    {"name": "Napa, CA", "lat": 38.2975, "lng": -122.2869},
    {"name": "Vallejo, CA", "lat": 38.1041, "lng": -122.2566},
    {"name": "Fairfield, CA", "lat": 38.2494, "lng": -122.0399},
    {"name": "Concord, CA", "lat": 37.9780, "lng": -122.0311},
    {"name": "Walnut Creek, CA", "lat": 37.9101, "lng": -122.0652},
    {"name": "Berkeley, CA", "lat": 37.8715, "lng": -122.2730},
    {"name": "Hayward, CA", "lat": 37.6688, "lng": -122.0808},
    {"name": "Fremont, CA", "lat": 37.5485, "lng": -121.9886},
    {"name": "Palo Alto, CA", "lat": 37.4419, "lng": -122.1430},
    {"name": "Mountain View, CA", "lat": 37.3861, "lng": -122.0839},
    {"name": "Sunnyvale, CA", "lat": 37.3688, "lng": -122.0363},
    {"name": "Santa Clara, CA", "lat": 37.3541, "lng": -121.9552},
    {"name": "Daly City, CA", "lat": 37.6879, "lng": -122.4702},
    {"name": "San Mateo, CA", "lat": 37.5630, "lng": -122.3255},
    {"name": "Redwood City, CA", "lat": 37.4852, "lng": -122.2364},
    {"name": "Livermore, CA", "lat": 37.6819, "lng": -121.7680},
    {"name": "Merced, CA", "lat": 37.3022, "lng": -120.4829},
    {"name": "Visalia, CA", "lat": 36.3302, "lng": -119.2921},
    {"name": "Hanford, CA", "lat": 36.3275, "lng": -119.6457},
    {"name": "Madera, CA", "lat": 36.9613, "lng": -120.0607},
    {"name": "San Luis Obispo, CA", "lat": 35.2828, "lng": -120.6596},
    {"name": "Paso Robles, CA", "lat": 35.6266, "lng": -120.6910},
    {"name": "Redding, CA", "lat": 40.5865, "lng": -122.3917},
    {"name": "Chico, CA", "lat": 39.7285, "lng": -121.8375},
    {"name": "Eureka, CA", "lat": 40.8021, "lng": -124.1637},
    {"name": "Ukiah, CA", "lat": 39.1502, "lng": -123.2078},
    {"name": "Yuba City, CA", "lat": 39.1404, "lng": -121.6169},
    {"name": "Davis, CA", "lat": 38.5449, "lng": -121.7405},
    {"name": "Roseville, CA", "lat": 38.7521, "lng": -121.2880},
    {"name": "Folsom, CA", "lat": 38.6779, "lng": -121.1761},
    {"name": "Elk Grove, CA", "lat": 38.4088, "lng": -121.3716},
]

CALIFORNIA_SEARCH_LOCATIONS = [
    *SOUTHERN_CALIFORNIA_SEARCH_LOCATIONS,
    *NORTHERN_CENTRAL_CALIFORNIA_SEARCH_LOCATIONS,
]

SEARCH_LOCATION_PRESETS = {
    "Colorado": COLORADO_SEARCH_LOCATIONS,
    "California": CALIFORNIA_SEARCH_LOCATIONS,
    "Southern California": SOUTHERN_CALIFORNIA_SEARCH_LOCATIONS,
    "Orange County / San Diego": ORANGE_COUNTY_SAN_DIEGO_SEARCH_LOCATIONS,
}

SEARCH_AREA_PRESETS = {
    preset_name: [location["name"] for location in locations]
    for preset_name, locations in SEARCH_LOCATION_PRESETS.items()
}

SEARCH_LOCATIONS = [
    *COLORADO_SEARCH_LOCATIONS,
    *CALIFORNIA_SEARCH_LOCATIONS,
    *ORANGE_COUNTY_SAN_DIEGO_SEARCH_LOCATIONS,
]

US_STATE_NAMES = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "DC": "District of Columbia",
}

PLACE_TYPES = [
    "restaurant",
    "cafe",
    "bar",
    "bakery",
    "store",
    "clothing_store",
    "shoe_store",
    "book_store",
    "furniture_store",
    "hardware_store",
    "home_goods_store",
    "pet_store",
    "florist",
    "beauty_salon",
    "hair_care",
    "spa",
    "gym",
    "laundry",
    "plumber",
    "electrician",
    "painter",
    "roofing_contractor",
    "general_contractor",
    "car_repair",
    "car_wash",
    "moving_company",
    "locksmith",
    "cleaning_service",
    "doctor",
    "dentist",
    "physiotherapist",
    "veterinary_care",
    "real_estate_agency",
    "insurance_agency",
    "lawyer",
    "accounting",
    "travel_agency",
    "photographer",
]

OVERTURE_CATEGORY_KEYWORDS = [
    "restaurant",
    "cafe",
    "coffee",
    "bar",
    "bakery",
    "store",
    "shop",
    "clothing",
    "shoe",
    "book",
    "furniture",
    "hardware",
    "home",
    "pet",
    "florist",
    "beauty",
    "hair",
    "spa",
    "gym",
    "fitness",
    "laundry",
    "plumber",
    "electrician",
    "painter",
    "roof",
    "contractor",
    "repair",
    "car_wash",
    "moving",
    "locksmith",
    "cleaning",
    "doctor",
    "dentist",
    "physio",
    "veterinary",
    "real_estate",
    "insurance",
    "lawyer",
    "account",
    "travel",
    "photograph",
]

TARGETING_CATEGORY_PRESETS = {
    "All supported": {
        "google_place_types": PLACE_TYPES,
        "overture_keywords": OVERTURE_CATEGORY_KEYWORDS,
    },
    "Home services": {
        "google_place_types": [
            "plumber",
            "electrician",
            "painter",
            "roofing_contractor",
            "general_contractor",
            "locksmith",
            "cleaning_service",
            "moving_company",
            "hardware_store",
            "home_goods_store",
        ],
        "overture_keywords": [
            "plumber",
            "electrician",
            "painter",
            "roof",
            "contractor",
            "locksmith",
            "cleaning",
            "moving",
            "hardware",
            "home",
            "repair",
        ],
    },
    "Contractor trades": {
        "google_place_types": [
            "general_contractor",
            "roofing_contractor",
            "plumber",
            "electrician",
            "painter",
        ],
        "overture_keywords": [
            "contractor",
            "roof",
            "plumber",
            "electrician",
            "painter",
            "remodel",
            "repair",
            "construction",
        ],
    },
    "Restaurants and food": {
        "google_place_types": [
            "restaurant",
            "cafe",
            "bar",
            "bakery",
        ],
        "overture_keywords": [
            "restaurant",
            "cafe",
            "coffee",
            "bar",
            "bakery",
            "food",
        ],
    },
    "Beauty and fitness": {
        "google_place_types": [
            "beauty_salon",
            "hair_care",
            "spa",
            "gym",
        ],
        "overture_keywords": [
            "beauty",
            "hair",
            "salon",
            "spa",
            "gym",
            "fitness",
        ],
    },
    "Health and wellness": {
        "google_place_types": [
            "doctor",
            "dentist",
            "physiotherapist",
            "veterinary_care",
            "spa",
            "gym",
        ],
        "overture_keywords": [
            "doctor",
            "dentist",
            "physio",
            "veterinary",
            "clinic",
            "spa",
            "fitness",
        ],
    },
    "Professional services": {
        "google_place_types": [
            "lawyer",
            "accounting",
            "insurance_agency",
            "real_estate_agency",
            "travel_agency",
            "photographer",
        ],
        "overture_keywords": [
            "lawyer",
            "attorney",
            "account",
            "insurance",
            "real_estate",
            "travel",
            "photograph",
        ],
    },
    "Real estate and home building": {
        "google_place_types": [
            "general_contractor",
            "real_estate_agency",
            "roofing_contractor",
            "painter",
            "home_goods_store",
        ],
        "overture_keywords": [
            "custom home builder",
            "luxury home builder",
            "home builder",
            "general contractor",
            "design build",
            "custom homes",
            "luxury remodel",
            "home remodeling",
            "real estate",
            "real estate agency",
            "real estate developer",
            "property developer",
            "builder",
            "construction",
            "architect",
            "interior designer",
            "land developer",
        ],
    },
    "Auto services": {
        "google_place_types": [
            "car_repair",
            "car_wash",
        ],
        "overture_keywords": [
            "auto",
            "car",
            "repair",
            "car_wash",
        ],
    },
}

OPPORTUNITY_FOCUS_PRESETS = {
    "any": "Any website opportunity",
    "no_website": "No website",
    "broken_site": "Broken website",
    "weak_site": "Weak or basic website",
    "high_review_no_website": "High-review no website",
    "premium_client_fit": "Premium client fit test",
    "new_business": "Newer business",
    "urgent_fix": "Urgent website fix",
}

SCAN_PROFILE_PRESETS = {
    "Custom": {
        "description": "Use the settings exactly as configured.",
    },
    "High-demand no website": {
        "description": "Prioritize businesses with clear demand signals and no owned website.",
        "opportunity_focus": "high_review_no_website",
        "min_rating": 4.3,
        "min_reviews": 25,
        "min_business_age_days": 180,
        "fast_test_mode": False,
        "skip_email_lookup": False,
        "tile_grid_size": 4,
    },
    "Broken website": {
        "description": "Prioritize businesses whose website is broken or unreachable.",
        "opportunity_focus": "broken_site",
        "min_rating": 4.0,
        "min_reviews": 10,
        "min_business_age_days": 90,
        "fast_test_mode": False,
        "skip_email_lookup": False,
        "tile_grid_size": 4,
    },
    "Weak site with reviews": {
        "description": "Prioritize businesses with live but weak/basic sites and review demand.",
        "opportunity_focus": "weak_site",
        "min_rating": 4.0,
        "min_reviews": 15,
        "min_business_age_days": 120,
        "fast_test_mode": False,
        "skip_email_lookup": False,
        "tile_grid_size": 4,
    },
    "Premium client fit test": {
        "description": "Test higher-budget prospects with strong demand signals and a pitchable website gap, including real sites.",
        "opportunity_focus": "premium_client_fit",
        "min_rating": 4.2,
        "min_reviews": 50,
        "min_business_age_days": 365,
        "fast_test_mode": True,
        "skip_email_lookup": False,
        "tile_grid_size": 4,
    },
    "Premium builders": {
        "description": "Find builder, developer, real-estate, and high-value home-service prospects without requiring a website gap.",
        "client_name": "",
        "target_profile_name": "Real estate and home building",
        "target_place_types": [
            "general_contractor",
            "real_estate_agency",
            "roofing_contractor",
        ],
        "target_category_keywords": [
            "custom home builder",
            "luxury home builder",
            "home builder",
            "general contractor",
            "design build",
            "custom homes",
            "luxury remodel",
            "home remodeling",
            "real estate agency",
            "real estate developer",
            "property developer",
            "builder",
            "construction company",
            "architect",
            "interior designer",
            "land developer",
            "residential builder",
        ],
        "opportunity_focus": "any",
        "min_rating": 3.5,
        "min_reviews": 3,
        "min_business_age_days": 180,
        "fast_test_mode": True,
        "fast_test_lead_limit": 250,
        "fast_test_total_run_cap": 350,
        "skip_email_lookup": False,
        "tile_grid_size": 4,
    },
    "New business": {
        "description": "Prioritize newer businesses that may need a first serious website.",
        "opportunity_focus": "new_business",
        "min_rating": 0.0,
        "min_reviews": 0,
        "min_business_age_days": 0,
        "fast_test_mode": False,
        "skip_email_lookup": False,
        "tile_grid_size": 4,
    },
    "Urgent fix": {
        "description": "Prioritize broken, SSL, parked, placeholder, or severe website failures.",
        "opportunity_focus": "urgent_fix",
        "min_rating": 3.8,
        "min_reviews": 5,
        "min_business_age_days": 30,
        "fast_test_mode": False,
        "skip_email_lookup": False,
        "tile_grid_size": 4,
    },
}

AUTOMATION_INTENSITY_PRESETS = {
    "normal": "Normal",
    "heavy_week": "Heavy this week",
}
