from __future__ import annotations

"""Static business-fit and matching config for the Colorado lead machine."""

EXCLUDE_CHAINS = {
    "starbucks",
    "dunkin",
    "mcdonalds",
    "mcdonald's",
    "burger king",
    "wendy's",
    "subway",
    "domino's",
    "pizza hut",
    "chipotle",
    "taco bell",
    "chick-fil-a",
    "kfc",
    "panera",
    "walmart",
    "target",
    "costco",
    "sam's club",
    "sams club",
    "kmart",
    "sears",
    "kohl's",
    "kohls",
    "macy's",
    "macys",
    "jcpenney",
    "jcpenney",
    "saks fifth avenue",
    "saks off 5th",
    "nordstrom",
    "nordstrom rack",
    "tj maxx",
    "tjmaxx",
    "t.j. maxx",
    "marshalls",
    "ross dress for less",
    "burlington coat factory",
    "five below",
    "big lots",
    "walgreens",
    "cvs",
    "safeway",
    "albertsons",
    "aldi",
    "king soopers",
    "city market",
    "natural grocers",
    "sprouts",
    "sprouts farmers market",
    "whole foods market",
    "trader joe's",
    "trader joes",
    "7-eleven",
    "circle k",
    "kum & go",
    "kum and go",
    "maverik",
    "maverik adventure's first stop",
    "maverik adventure s first stop",
    "conoco",
    "conoco phillips",
    "phillips 66",
    "76",
    "sinclair",
    "texaco",
    "valero",
    "citgo",
    "mobil",
    "exxon",
    "exxonmobil",
    "amoco",
    "bp",
    "ampm",
    "arco",
    "quiktrip",
    "qt",
    "casey's",
    "caseys",
    "pilot",
    "pilot flying j",
    "flying j",
    "love's",
    "loves",
    "speedway",
    "loaf n jug",
    "loaf 'n jug",
    "shell",
    "chevron",
    "jiffy lube",
    "autozone",
    "discount tire",
    "america's tire",
    "americas tire",
    "big o tires",
    "firestone complete auto care",
    "pep boys",
    "valvoline",
    "chase",
    "bank of america",
    "wells fargo",
    "state farm",
    "state farm insurance",
    "allstate",
    "allstate insurance",
    "farmers insurance",
    "farmers insurance group",
    "geico",
    "geico local office",
    "nationwide",
    "nationwide insurance",
    "american family insurance",
    "amfam",
    "liberty mutual",
    "progressive",
    "travelers",
    "the hartford",
    "shelter insurance",
    "fred loya insurance",
    "goosehead insurance",
    "aaa insurance",
    "planet fitness",
    "anytime fitness",
    "ups store",
    "fedex",
    "marriott",
    "hilton",
    "holiday inn",
    "best western",
    "great clips",
    "supercuts",
    "massage envy",
    "aspen dental",
    "servpro",
    "u-haul",
    "enterprise",
    "hertz",
    "re/max",
    "keller williams",
    "century 21",
    "uchealth",
    "h&m",
    "hm",
    "zara",
    "old navy",
    "banana republic",
    "forever 21",
    "american eagle",
    "aerie",
    "hollister",
    "abercrombie",
    "abercrombie & fitch",
    "victoria's secret",
    "victorias secret",
    "bath & body works",
    "bath and body works",
    "carter's",
    "carters",
    "buckle",
    "anthropologie",
    "urban outfitters",
    "free people",
    "madewell",
    "maurices",
    "tillys",
    "zumiez",
    "vans store",
    "journeys",
    "journeys kidz",
    "shoe palace",
    "shoe dept",
    "shoe dept. encore",
    "foot locker",
    "kids foot locker",
    "champs sports",
    "jd sports",
    "finish line",
    "famous footwear",
    "rack room shoes",
    "designer shoe warehouse",
    "dsw",
    "lids",
    "spencer's",
    "spencers",
    "hot topic",
    "torrid",
    "earthbound",
    "earthbound trading co",
    "plato's closet",
    "platos closet",
    "once upon a child",
    "style encore",
    "kid to kid",
    "fleet feet",
    "kay jewelers",
    "zales",
    "jared",
    "pandora",
    "helzberg diamonds",
    "pandora jewelry",
    "pro image sports",
    "scrub authority",
    "best buy",
    "apple store",
    "barnes & noble",
    "barnes and noble",
    "petco",
    "petsmart",
    "homegoods",
    "world market",
    "ulta beauty",
    "ulta",
    "sephora",
    "sally beauty",
    "gamestop",
    "cricket wireless",
    "metro by t-mobile",
    "at&t",
    "verizon",
    "t-mobile",
    "dick's sporting goods",
    "dicks sporting goods",
    "big 5 sporting goods",
    "scheels",
    "sportsman's warehouse",
    "cabela's",
    "cabelas",
    "bass pro shops",
    "rei co-op",
    "lululemon",
    "athleta",
    "vuori",
    "arcteryx",
    "arc'teryx",
    "patagonia",
    "gucci",
    "louis vuitton",
    "prada",
    "burberry",
    "saint laurent",
    "ysl",
    "chanel",
    "dior",
    "hermes",
    "cartier",
    "tiffany & co",
    "tiffany and co",
    "rolex boutique",
    "omega boutique",
    "tag heuer",
    "versace",
    "balenciaga",
    "valentino",
    "moncler",
    "canada goose",
    "rimowa",
    "denver mattress",
    "mattress firm",
    "sleep number",
    "ashley store",
    "ashley furniture",
    "american furniture warehouse",
    "furniture row",
    "michaels",
    "hobby lobby",
    "joann",
    "goodwill",
    "arc thrift",
    "arc thrift stores",
    "murdoch's ranch & home supply",
    "murdochs ranch & home supply",
    "big r",
    "boot barn",
    "red wing shoes",
    "mr. handyman",
    "mr handyman",
    "molly maid",
    "merry maids",
    "two maids",
    "two maids & a mop",
    "the maids",
    "stanley steemer",
    "chem-dry",
    "chemdry",
    "servicemaster",
    "servicemaster clean",
    "restoration 1",
    "paul davis restoration",
    "rainsoft",
    "mr. rooter",
    "mr rooter",
    "roto-rooter",
    "roto rooter",
    "benjamin franklin plumbing",
    "one hour heating",
    "one hour heating & air conditioning",
    "aire serv",
    "mosquito joe",
    "mosquito joe's",
    "mosquito authority",
    "lawn doctor",
    "weed man",
    "trugreen",
    "spring-green",
    "spring green",
    "mosquito squad",
    "the grounds guys",
    "five star painting",
    "certapro painters",
    "certapro",
    "college hunks hauling junk",
    "1-800-got-junk",
    "1 800 got junk",
    "junk king",
    "the junkluggers",
    "two men and a truck",
    "pods",
    "budget truck rental",
    "penske",
    "home instead",
    "comfort keepers",
    "brightspring",
    "right at home",
    "visiting angels",
    "kumon",
    "mathnasium",
    "sylvan learning",
    "huntington learning",
    "club pilates",
    "orangetheory",
    "orangetheory fitness",
    "f45 training",
    "f45",
    "burn boot camp",
    "pure barre",
    "cyclebar",
    "stretch zone",
    "hand and stone",
    "hand & stone",
    "european wax center",
    "drybar",
    "sport clips",
    "fantastic sams",
    "cost cutters",
    "smartstyle",
    "regis salon",
    "jackson hewitt",
    "h&r block",
    "hr block",
    "liberty tax",
    "snap fitness",
    "crunch fitness",
    "gold's gym",
    "golds gym",
    "la fitness",
    "lifetime fitness",
    "life time fitness",
    "equinox",
    "youfit",
    "title boxing",
    "9round",
}

CHAIN_EXACT_ONLY = {
    "gap",
    "pink",
    "express",
    "vans",
    "rei",
    "ross",
    "burlington",
    "at home",
    "76",
    "qt",
    "bp",
}

EXCLUDE_ORG_KEYWORDS = [
    "hospital",
    "medical center",
    "health system",
    "urgent care",
    "children's hospital",
    "community health",
    "legal group",
    "law group",
    "medical group",
    "dental group",
    "corporate",
    "holdings",
    "enterprises",
    "international",
]

BAD_FIT_NAME_KEYWORDS = {
    "gas station",
    "fuel center",
    "fuel station",
    "travel center",
    "truck stop",
    "hotel",
    "motel",
    "resort",
    "lodge",
    "hostel",
    "inn",
    "bed breakfast",
    "vacation rental",
    "timeshare",
    "campground",
    "rv park",
    "zoo",
    "aquarium",
    "museum",
    "stadium",
    "arena",
    "amphitheater",
    "amphitheatre",
    "theater",
    "theatre",
    "event center",
    "conference center",
    "convention center",
    "visitor center",
    "welcome center",
    "city hall",
    "courthouse",
    "public library",
    "library",
    "public schools",
    "school district",
    "elementary school",
    "middle school",
    "high school",
    "charter school",
    "community college",
    "state college",
    "state university",
    "university of",
    "campus",
    "university",
    "college",
    "school",
    "airport",
    "union station",
    "headquarters",
    "corporate office",
    "distribution center",
    "fulfillment center",
    "no sales",
    "shopping mall",
    "shopping center",
    "outlet mall",
    "outlets",
}

BAD_FIT_CATEGORY_KEYWORDS = {
    "gas station",
    "fuel",
    "convenience store",
    "truck stop",
    "hotel",
    "motel",
    "lodging",
    "resort",
    "hostel",
    "vacation rental",
    "timeshare",
    "campground",
    "rv park",
    "tourist attraction",
    "museum",
    "zoo",
    "aquarium",
    "stadium",
    "arena",
    "amphitheater",
    "amphitheatre",
    "theater",
    "theatre",
    "event venue",
    "conference center",
    "convention center",
    "park",
    "visitor center",
    "welcome center",
    "library",
    "public school",
    "school district",
    "elementary school",
    "middle school",
    "high school",
    "charter school",
    "community college",
    "state college",
    "state university",
    "campus",
    "university",
    "college",
    "school",
    "airport",
    "government",
    "civic",
}

BAD_FIT_GOOGLE_TYPES = {
    "gas_station",
    "convenience_store",
    "lodging",
    "rv park",
    "campground",
    "tourist attraction",
    "museum",
    "zoo",
    "aquarium",
    "stadium",
    "amusement park",
    "movie theater",
    "park",
    "library",
    "city hall",
    "courthouse",
    "school",
    "primary school",
    "secondary school",
    "preschool",
    "campus",
    "university",
    "airport",
    "bus station",
    "train station",
    "transit station",
    "light rail station",
    "subway station",
    "local government office",
    "place of worship",
    "cemetery",
}

WEAK_MATCH_NAME_TOKENS = {
    "colorado",
    "company",
    "companies",
    "service",
    "services",
    "solutions",
    "group",
    "partners",
    "team",
    "family",
    "home",
    "center",
    "centre",
    "professional",
    "professionals",
    "business",
    "enterprises",
    "enterprise",
    "local",
    "best",
}
